example_location: "examples"
api_groups:
  - "AdmissionRegistration"
  - "ApiExtensions"
  - "InternalApiserver"
  - "ApiRegistration"
  - "Apps"
  - "AuditRegistration"
  - "Authentication"
  - "Authorization"
  - "Autoscaling"
  - "Batch"
  - "Certificates"
  - "Coordination"
  - "Core"
  - "Discovery"
  - "Extensions"
  - "FlowControl"
  - "Meta"
  - "Networking"
  - "Node"
  - "Policy"
  - "Rbac"
  - "Resource"
  - "Scheduling"
  - "Settings"
  - "Storage"
  - "StorageMigration"
resource_categories:
  - name: "Workloads APIs"
    include: "workloads"
    resources:
    - name: Container
      version: v1
      group: core
      description_warning: "Containers are only ever created within the context of a <a href=\"#pod-v1-core\">Pod</a>.  This is usually done using a Controller.  See Controllers: <a href=\"#deployment-v1-apps\">Deployment</a>, <a href=\"#job-v1-batch\">Job</a>, or <a href=\"#statefulset-v1-apps\">StatefulSet</a>"
    - name: CronJob
      version: v1
      group: batch
    - name: DaemonSet
      version: v1
      group: apps
    - name: Deployment
      version: v1
      group: apps
    - name: Job
      version: v1
      group: batch
    - name: Pod
      version: v1
      group: core
      description_warning: "It is recommended that users create Pods only through a Controller, and not directly.  See Controllers: <a href=\"#deployment-v1-apps\">Deployment</a>, <a href=\"#job-v1-batch\">Job</a>, or <a href=\"#statefulset-v1-apps\">StatefulSet</a>."
    - name: ReplicaSet
      version: v1
      group: apps
      description_warning: "In many cases it is recommended to create a <a href=\"#deployment-v1-apps\">Deployment</a> instead of ReplicaSet."
    - name: ReplicationController
      version: v1
      group: core
      description_warning: "In many cases it is recommended to create a <a href=\"#deployment-v1-apps\">Deployment</a> instead of a ReplicationController."
    - name: StatefulSet
      version: v1
      group: apps
  - name: "Service APIs"
    include: "servicediscovery"
    resources:
    - name: Endpoints
      version: v1
      group: core
    - name: EndpointSlice
      version: v1
      group: discovery
    - name: Ingress
      version: v1
      group: networking
    - name: IngressClass
      version: v1
      group: networking
    - name: Service
      version: v1
      group: core
  - name: "Config and Storage APIs"
    include: "config"
    resources:
    - name: ConfigMap
      version: v1
      group: core
    - name: CSIDriver
      version: v1
      group: storage
    - name: CSINode
      version: v1
      group: storage
    - name: CSIStorageCapacity
      version: v1
      group: storage
    - name: Secret
      version: v1
      group: core
    - name: PersistentVolumeClaim
      version: v1
      group: core
      description_note: "A <a href=\"#persistentvolume-v1-core\">PersistentVolume</a> must be allocated in the cluster to use this."
    - name: StorageClass
      version: v1
      group: storage
    - name: StorageVersionMigration
      version: v1alpha1
      group: storagemigration
    - name: Volume
      version: v1
      group: core
    - name: VolumeAttachment
      version: v1
      group: storage
    - name: VolumeAttributesClass
      version: v1beta1
      group: storage
  - name: "Metadata APIs"
    include: "meta"
    resources:
    - name: ClusterTrustBundle
      version: v1beta1
      group: certificates
    - name: ControllerRevision
      version: v1
      group: apps
    - name: CustomResourceDefinition
      version: v1
      group: apiextensions
    - name: DeviceClass
      version: v1beta2
      group: resource
    - name: DeviceTaintRule
      version: v1alpha3
      group: resource
    - name: Event
      version: v1
      group: events
    - name: LimitRange
      version: v1
      group: core
    - name: HorizontalPodAutoscaler
      version: v2
      group: autoscaling
    - name: MutatingWebhookConfiguration
      version: v1
      group: admissionregistration
    - name: PodTemplate
      version: v1
      group: core
    - name: PodDisruptionBudget
      version: v1
      group: policy
    - name: PriorityClass
      version: v1
      group: scheduling
    - name: ResourceClaim
      version: v1beta2
      group: resource
    - name: ResourceClaimTemplate
      version: v1beta2
      group: resource
    - name: ResourceSlice
      version: v1beta2
      group: resource
    - name: ValidatingAdmissionPolicy
      version: v1
      group: admissionregistration
    - name: ValidatingAdmissionPolicyBinding
      version: v1
      group: admissionregistration
    - name: ValidatingWebhookConfiguration
      version: v1
      group: admissionregistration
  - name: "Cluster APIs"
    include: "cluster"
    resources:
    - name: APIService
      version: v1
      group: apiregistration
    - name: Binding
      version: v1
      group: core
    - name: CertificateSigningRequest
      version: v1
      group: certificates
    - name: ClusterRole
      version: v1
      group: rbac
    - name: ClusterRoleBinding
      version: v1
      group: rbac
    - name: ComponentStatus
      version: v1
      group: core
    - name: FlowSchema
      version: v1
      group: flowcontrol
    - name: IPAddress
      version: v1
      group: networking
    - name: Lease
      version: v1
      group: coordination
    - name: LeaseCandidate
      version: v1beta1
      group: coordination
    - name: LocalSubjectAccessReview
      version: v1
      group: authorization
    - name: Namespace
      version: v1
      group: core
    - name: Node
      version: v1
      group: core
    - name: PersistentVolume
      version: v1
      group: core
      description_note: "These are assigned to <a href=\"#pod-v1-core\">Pods</a> using <a href=\"#persistentvolumeclaim-v1-core\">PersistentVolumeClaims</a>."
    - name: PriorityLevelConfiguration
      version: v1
      group: flowcontrol
    - name: ResourceQuota
      version: v1
      group: core
    - name: Role
      version: v1
      group: rbac
    - name: RoleBinding
      version: v1
      group: rbac
    - name: RuntimeClass
      version: v1
      group: node
    - name: SelfSubjectAccessReview
      version: v1
      group: authorization
    - name: SelfSubjectReview
      version: v1
      group: authentication
    - name: SelfSubjectRulesReview
      version: v1
      group: authorization
    - name: ServiceAccount
      version: v1
      group: core
    - name: ServiceCIDR
      version: v1
      group: networking
    - name: StorageVersion
      version: v1alpha1
      group: apiserverinternal
    - name: StorageVersionMigration
      version: v1alpha1
      group: storagemigration
    - name: SubjectAccessReview
      version: v1
      group: authorization
    - name: TokenRequest
      version: v1
      group: authentication
    - name: TokenReview
      version: v1
      group: authentication
    - name: NetworkPolicy
      version: v1
      group: networking
    - name: MutatingAdmissionPolicy
      version: v1alpha1
      group: admissionregistration
    - name: MutatingAdmissionPolicyBinding
      version: v1alpha1
      group: admissionregistration

operation_categories:
  - name: "Proxy Operations"
    operation_types:
    - name: Create Connect Portforward
      match: connect${group}${version}Post(Namespaced)?${resource}Portforward
    - name: Create Connect Proxy
      match: connect${group}${version}Post(Namespaced)?${resource}Proxy
    - name: Create Connect Proxy Path
      match: connect${group}${version}Post(Namespaced)?${resource}ProxyWithPath
    - name: Create Proxy
      match: proxy${group}${version}POST(Namespaced)?${resource}
    - name: Create Proxy Path
      match: proxy${group}${version}POST(Namespaced)?${resource}WithPath
    - name: Delete Connect Proxy
      match: connect${group}${version}Delete(Namespaced)?${resource}Proxy
    - name: Delete Connect Proxy Path
      match: connect${group}${version}Delete(Namespaced)?${resource}ProxyWithPath
    - name: Delete Proxy
      match: proxy${group}${version}DELETE(Namespaced)?${resource}
    - name: Delete Proxy Path
      match: proxy${group}${version}DELETE(Namespaced)?${resource}WithPath
    - name: Get Connect Portforward
      match: connect${group}${version}Get(Namespaced)?${resource}Portforward
    - name: Get Connect Proxy
      match: connect${group}${version}Get(Namespaced)?${resource}Proxy
    - name: Get Connect Proxy Path
      match: connect${group}${version}Get(Namespaced)?${resource}ProxyWithPath
    - name: Get Proxy
      match: proxy${group}${version}GET(Namespaced)?${resource}
    - name: Get Proxy Path
      match: proxy${group}${version}GET(Namespaced)?${resource}WithPath
    - name: Head Connect Proxy
      match: connect${group}${version}Head(Namespaced)?${resource}Proxy
    - name: Head Connect Proxy Path
      match: connect${group}${version}Head(Namespaced)?${resource}ProxyWithPath
    - name: Replace Connect Proxy
      match: connect${group}${version}Put(Namespaced)?${resource}Proxy
    - name: Replace Connect Proxy Path
      match: connect${group}${version}Put(Namespaced)?${resource}ProxyWithPath
    - name: Replace Proxy
      match: proxy${group}${version}PUT(Namespaced)?${resource}
    - name: Replace Proxy Path
      match: proxy${group}${version}PUT(Namespaced)?${resource}WithPath
  - name: "Misc Operations"
    default: true
    operation_types:
    - name: Read Scale
      match: read${group}${version}(Namespaced)?${resource}Scale
    - name: Replace Scale
      match: replace${group}${version}(Namespaced)?${resource}Scale
    - name: Patch Scale
      match: patch${group}${version}(Namespaced)?${resource}Scale
    - name: Rollback
      match: create${group}${version}(Namespaced)?${resource}Rollback
    - name: Read Log
      match: read${group}${version}(Namespaced)?${resource}Log
    - name: Get Connect Exec
      match: connect${group}${version}Get(Namespaced)?${resource}Exec
    - name: Create Connect Exec
      match: connect${group}${version}Post(Namespaced)?${resource}Exec
    - name: Get Connect Attach
      match: connect${group}${version}Get(Namespaced)?${resource}Attach
    - name: Create Connect Attach
      match: connect${group}${version}Post(Namespaced)?${resource}Attach

# List of *partial* operation IDs for matching. All matched operations are
# excluded from the reference doc.
excluded_operations:
  - connectCoreV1Patch
  - createCoreV1NamespacedPodBinding
  - getCodeVersion
  - logFileHandler
  - logFileListHandler
  - replaceCoreV1NamespaceFinalize
  - V1beta1CertificateSigningRequestApproval
  - V1CertificateSigningRequestApproval
  - V1beta1NamespacedReplicationControllerDummyScale
  - getServiceAccountIssuerOpenIDConfiguration
  - getServiceAccountIssuerOpenIDKeyset

# Map from group name to its full name
group_full_names:
  admission: admission
  admissionregistration: admissionregistration.k8s.io
  apiextensions: apiextensions.k8s.io
  apiregistration: apiregistration.k8s.io
  apiserverinternal: internal.apiserver.k8s.io
  apps: apps
  authentication: authentication.k8s.io
  authorization: authorization.k8s.io
  autoscaling: autoscaling
  batch: batch
  certificates: certificates.k8s.io
  coordination: coordination.k8s.io
  core: core
  discovery: discovery.k8s.io
  events: events.k8s.io
  extensions: extensions
  flowcontrol: flowcontrol.apiserver.k8s.io
  meta: meta
  networking: networking.k8s.io
  node: node.k8s.io
  policy: policy
  rbac: rbac.authorization.k8s.io
  resource: resource.k8s.io
  scheduling: scheduling.k8s.io
  storage: storage.k8s.io
  storagemigration: storagemigration.k8s.io

# The map from the group as the resource sees it to the group as the operation
# sees it.
operation_group_map:
  rbac: RbacAuthorization
  flowcontrol: FlowcontrolApiserver
  apiserverinternal: InternalApiserver
